### ISSUE TITLE
duplicate search result

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#20]
When searching for 'test' I get two duplicate results, all images are the same but there is a duplicate link in there as well. Is this a problem with the implementation of CloudSearch or are there two distinct records with the same URI?

**Comment by tomkr** [comment]
It looks like all images are duplicated in the cloud search database: once with the image id as the cloudsearch id and one with a different unique cloudsearch id. Since the image id is the same in both cases, they are completely similar for our purposes. So it looks like the ones with the image id in cloudsearch can be cleaned up.
