### ISSUE TITLE
Visual tweaks to text page (Wordpress)

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#28]
- [x] afstand tussen zoekbox en tekstbox moet 82px zijn.
- [x] titel moet Raleway Extrabold zijn, font-size: 48px. 
- [x] p-tekst moet Ubuntu (geen Raleway) zijn 24px / line-height: 30px.
- [x] tussenkop moet zijn Raleway Extrabold, font-size: 24px
- [x] een link moet decoration: underline hebben en gewoon zwart zijn (niet blauw).

**Comment by Taskamp** [comment]
It looks good. There are a few small modifications:

-[x] What is the font size of the normal text? It looks like it is 18. It should be two or so sizes smaller, and also the title should be a bit smaller. So I think: Title: 34, normal text: 15, h1, h2 and h3 should stay the same. I know that it differs from the design but if I see the actual text, it is just too large.
-[x] Bullet points and numbered text is too small. Can you enable it so that also bullet pointed text is the same size as normal text.
-[x] ‘ turns into footnote. Can you disable that mode?
