### ISSUE TITLE
Search does not seem to pick up all queries

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#67]

**Comment by mzeinstra** [comment]
Example searching for 'museon' should provide a list of about 8000 records.
An example of an item that should appear is:
http://dev.embedr.eu/europeana___2021657__216359/
Also searching for its title should yield their results.

It appears that the search does not search over all fields that are available.

Search uses AWS cloudsearch. 

It does not appear to be a problem in CloudSearch: https://github.com/klokantech/hawk/issues/69 

See https://github.com/tomkr/embedr/issues/11 for a detailed explanation on how Cloudsearch is implemented and which facets kan be used.

**Comment by arjan** [comment]
The issue is that the frontend filters the results by the CC license used.
I added CC-BY-3.0 to the set of 'freely' licenses in 79ca2c02a40247cd54dd849ae1642c748e3ef012

"Museon familieportret" now returns a value like it should.
However it could be still the case that there are other results missing due to incomplete or wrong license information, or that the license list around https://github.com/tomkr/embedr/blob/master/app/scripts/components/search_mixin.js#L3 is still incomplete.
