### ISSUE TITLE
Different viewer options for display in embedded images iframe

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#81]
Currently the display of embedded images on sites that are not on embedr.eu display all options that are available on embedr.eu

We want to change that. As embedded images usually don't have access to the full screen its interaction is flawed.

We want to reduce this functionality to only the zoom buttons and a button for embed. pressing this last button would bring the user to the embedr.eu website of the image.

![pasted image at 2015_10_09 04_57 pm](https://cloud.githubusercontent.com/assets/5627431/10877366/dcde8ade-8145-11e5-9c65-2378794b639c.png)

I foresee a couple of ways to solve this.

1. automatically detect when the iframe is not embedded on embedr.eu
This is costly and probably has some security risks for the end-user

2. use a GET variable to communicate which set-up to use. 
I prefer this one, use a negative variable for external embedding. i.e. do something like  http://media.embedr.eu/Rijksmuseum_SK-C-5?f=1 for embedding within embedr.eu and
http://media.embedr.eu/Rijksmuseum_SK-C-5 for embedding on external platforms. This keeps the url cleaner for external use and makes the default the version with less functionality.

**Comment by tomkr** [comment]
This seems to be related to #85. It's a bit clearer to me now. So if I understand correctly the following needs to change:

* [ ] The current viewer has to be shown when a GET-parameter is set.
* [ ] Without the GET-parameter the viewer has to only show zoom-in and zoom-out buttons.
* [ ] Without the GET-parameter the viewer gets an embed-button that is simply a hyperlink the the full viewer on the embedr.eu page.

Since this requires a lot of changes to the media.embedr.eu page, I think it may be smart to move the javascript and css files for the viewer to the embedr.eu server. That way they can be changed without further PRs. So an additional requirement:

* [ ] Serve static assets for viewer from embedr.eu.

Agreed?

**Comment by mzeinstra** [comment]
I agree with you on the first three. I want to complete the changes to include https://github.com/tomkr/embedr/issues/85

[ ] When a parameter is set (nozoom=1 for example) we would get a viewer that has no zoom buttons and does not allow zoom at all. the embed button is simply a hyperlink to the full viewer on embedr.eu 

also

[ ] the hyperlink to embedr.eu is target="_blank"

As the hosting and load balancer is on our amazon service I think it would not be a good idea to move the static assets to our service. you can do that in a test environment, but not on development.

**Comment by tomkr** [comment]
Is there a way for me to get access to a development setup of the media.embedr.eu application? Doing PRs in the blind is not a very productive way of working, in my opinion.

**Comment by mzeinstra** [comment]
I'll see what I can do: https://github.com/klokantech/hawk/issues/74

**Comment by tomkr** [comment]
There will be three possible configurations for the viewer:

* The one that is currently used on embedr.eu
* The default embed view with only zoom in and zoom out buttons and an embed button with a link to embedr in a new tab (this one has no params)
* The embed view that is specified in #85 (not zoomable with only embed link to embedr in new tab)

**Comment by tomkr** [comment]
This can be tested on http://dev.embedr.eu/viewer/

**Comment by mzeinstra** [comment]
I can confirm that the above described development has been implemented. Closing the ticket.
