### ISSUE TITLE
Non-zoomable embeddeable version

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#85]
* [x] Checkbox that toggles between `nozoom=1` and nothing

We have a non-zoomable embeddable image on the roadmap.

![472ce3b0-6371-11e5-8428-7ccaf9005c5f](https://cloud.githubusercontent.com/assets/5627431/10877926/c5ee97ba-814a-11e5-892c-3f587aa0538b.jpg)
Text after tick box should be 'make embedded image zoomable'

When the box it checked it should add a parameter to the iframe src that tells the iframe not allow a zoomable image. Only display the embed button, when clicked the user is directed to image page of the relevant image on embedr.eu

**Comment by tomkr** [comment]
If I understand correctly there should be an option to have a viewer that can't be zoomed. Something like http://media.embedr.eu/Rijksmuseum_wiki_SK-C-5?zoom=false which only displays the embed button. I don't exactly understand what the embed button is then supposed to do. What is the image page?

I also don't understand why you would want to allow a user to embed a limited version of the viewer? This ticket is a lot of work (since everything that is now baked in has to be made configurable) for little gain in my opinion. And it requires a lot of modifications to the viewer, so it needs to be in a PR on the media.embedr.eu code.

**Comment by mzeinstra** [comment]
Yes it would require a PR on media.embedr.eu

We want this for UX purposes. I understand that it could be some work. see #81 for further details.

**Comment by tomkr** [comment]
Closing this, as discussion is taking place at #81 anyway.

**Comment by mzeinstra** [comment]
This also has an interface element, the checkbox. Is that solved as well?

**Comment by tomkr** [comment]
Available for testing on dev.ember.eu.

**Comment by mzeinstra** [comment]
I see that there are some margins that are not followed. I'll try to have an updated css for you by the end of the day.

**Comment by mzeinstra** [comment]
The User interface seems to be correctly implemented except for one item:

* [ ] make the checkbox black conform the design

Otherwise you can put this in a pull request to Klokan I believe.

**Comment by tomkr** [comment]
Changing the checkbox to something non-standard is a lot of work. We skipped it for the radio buttons in the advanced search. Perhaps this can be postponed as well.

**Comment by mzeinstra** [comment]
I see, ok
